video:
  image: itmadublin/ffmpeg-concat
  environment:
    - READ_DIR=/video_input
    - WRITE_DIR=/video_output
    - NAME=access_copy
    - DURATION=10
  volumes:
    - /Volumes/ProToolsWorkspace_2012/Glen Fiddle Week 2016/1 August/Meehans house/:/video_input/
    - /Volumes/ProToolsWorkspace_2012/processed_video/:/video_output/
