video:
  # image: itmadublin/ffmpeg-concat
  build: '.'
  environment:
    - READ_DIR=/video_input
    - WRITE_DIR=/video_output
    - NAME=access_copy
    - DURATION=10
  volumes:
    - /Volumes/ITMAVIDEO/VIDEO/FR_Bag_Store/080716_wcss_lunchtime_pipes/data/080716_wcss_lunchtime_piping_recital/Video/:/video_input/
    - /Users/itma/code/itma.ffmpeg-concat/:/video_output/
